config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :students do
     member do
      get :register
      post :assign
    end
  end
  root 'home#index'

  devise_for :users , controllers: {
         sessions: 'users/sessions',
         registrations: 'users/registrations',
         confirmations: 'users/confirmations'  }

      get 'logged_in', to: 'home#logged_in', as: :logged_in_home
      get 'logged_out', to: 'home#logged_out', as: :logged_out_home
      get 'signed_up', to: 'home#signed_up', as: :signed_up_home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @courses = current_user.courses
  end

  def register
    @current_user
    @courses = Course.pluck(:name)
  end

  def assign
    @usrcourse = UserCourse.new
    status, message = @usrcourse.register_course(params[:course],params[:id],current_user)
    if status
      redirect_to student_path(current_user), notice: message
    else
      render :register
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/register.html.erb
<h2>Register </h2>

<%= form_with url: assign_student_path do |f| %>
  <%= f.select :course, options_for_select(Course.pluck(:name)), :prompt => 'Select One' %>
  <%= f.submit "Register" %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path %>
<% end %>

app/views/students/show.html.erb
<h1> Show User Courses </h1>

<br/>
<% @courses.each do |course| %>
  <%= course.name %>
<% end %>

<br/>
<br/>
<br/>
<%= link_to "Back", root_path %>

<br/>
<br/>

<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path %>
<% end %>