config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :students do
     member do
      get :register
      post :assign
    end
  end
  root 'home#index'

  devise_for :users , controllers: {
         sessions: 'users/sessions',
         registrations: 'users/registrations',
         confirmations: 'users/confirmations'  }

      get 'logged_in', to: 'home#logged_in', as: :logged_in_home
      get 'logged_out', to: 'home#logged_out', as: :logged_out_home
      get 'signed_up', to: 'home#signed_up', as: :signed_up_home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def logged_in
    puts "---------Logged_in"
  end

  def logged_out
  end

  def signed_up
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>This is Home-Page</h1>


<br/><br/>

<% if user_signed_in? %>
  <%= link_to "My Courses", student_path(current_user) %>
  <%= link_to "Register", register_student_path(current_user) %>
  <%= link_to "Logout", destroy_user_session_path %>
  <br/><br/>
<% else %>
  <%#= link_to "Signup", new_user_registration_path %>
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/home/logged_in.html.erb
<h1> Main User Page </h1>

Welcome:
<%= current_user.username %>
<br/>


<%= link_to "Register", register_register_path(current_user) %>
<br/><br/>
<%= link_to "Logout", destroy_user_session_path %>

app/views/home/logged_out.html.erb
<h1> After Logout Page </h1>

<%= link_to "Login", new_user_session_path %>

app/views/home/signed_up.html.erb
<h1> After Signup Page </h1>

<%= link_to "Logout", destroy_user_session_path %>